In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv(r"D:\Machine_Learning_Projects\Spam_detection\data\spam_email_dataset.csv")

In [3]:
data

,email_id,subject,email_text,num_words,num_characters,num_exclamation_marks,num_links,has_suspicious_link,num_attachments,has_attachment,sender_email,sender_domain,sender_reputation_score,email_hour,email_day_of_week,is_weekend,num_recipients,contains_money_terms,contains_urgency_terms,label
0,0,Weekly Report,budget review - Statement our I claim world st...,19,114,0,2,0,2,1,lctvdzm@outlook.com,outlook.com,0.66,19,3,0,23,0,0,0
1,1,Project Update,team sync - President series today already. In...,18,114,0,7,0,0,0,pxyldmi@company.com,company.com,0.95,4,4,0,16,1,0,0
2,2,🔥WIN BIG NOW!!,win free urgent offer limited limited urgent u...,19,126,0,4,1,1,1,atvanls@unknownmail.cc,unknownmail.cc,0.68,3,0,0,10,1,1,1
3,3,🔥WIN BIG NOW!!,guarantee click now cash offer click now guara...,16,101,0,7,1,1,1,qalxcnf@chealdealz.xyz,chealdealz.xyz,0.69,19,5,1,25,1,1,1
4,4,Meeting Reminder,team sync - Significant property hotel not add...,18,111,0,7,1,2,1,xoiccxl@yahoo.com,yahoo.com,0.67,4,5,1,8,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,🔥WIN BIG NOW!!,free win cash win guarantee urgent free win li...,22,136,0,5,1,0,0,fefsrcz@unknownmail.cc,unknownmail.cc,0.68,8,1,0,29,1,1,1
9996,9996,You are selected!!!,click now free guarantee free win click now wi...,26,158,0,2,0,0,0,yxyctux@chealdealz.xyz,chealdealz.xyz,0.76,2,3,0,29,0,1,1
9997,9997,You are selected!!!,offer cash win limited click now cash limited ...,21,124,0,3,1,1,1,tkvqnki@unknownmail.cc,unknownmail.cc,0.69,6,1,0,25,0,1,1
9998,9998,Meeting Reminder,budget review - Many result affect idea.,7,40,0,1,0,2,1,wmvnrbn@outlook.com,outlook.com,0.80,7,2,0,18,0,0,0
9999,9999,Schedule Confirmation,budget review - Day measure few alone decade a...,15,86,0,3,0,1,1,tpydjum@gmail.com,gmail.com,0.95,0,2,0,10,0,0,0

In [5]:
clean_data=data[["subject","email_text","label"]]

In [6]:
clean_data

,subject,email_text,label
0,Weekly Report,budget review - Statement our I claim world st...,0
1,Project Update,team sync - President series today already. In...,0
2,🔥WIN BIG NOW!!,win free urgent offer limited limited urgent u...,1
3,🔥WIN BIG NOW!!,guarantee click now cash offer click now guara...,1
4,Meeting Reminder,team sync - Significant property hotel not add...,0
...,...,...,...
9995,🔥WIN BIG NOW!!,free win cash win guarantee urgent free win li...,1
9996,You are selected!!!,click now free guarantee free win click now wi...,1
9997,You are selected!!!,offer cash win limited click now cash limited ...,1
9998,Meeting Reminder,budget review - Many result affect idea.,0
9999,Schedule Confirmation,budget review - Day measure few alone decade a...,0

In [7]:
clean_data["cleaned"]=clean_data["subject"] + " " + clean_data["email_text"]

C:\Users\Vivek\AppData\Local\Temp\ipykernel_21440\2808914679.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_data["cleaned"]=clean_data["subject"] + " " + clean_data["email_text"]

In [8]:
clean_data

,subject,email_text,label,cleaned
0,Weekly Report,budget review - Statement our I claim world st...,0,Weekly Report budget review - Statement our I ...
1,Project Update,team sync - President series today already. In...,0,Project Update team sync - President series to...
2,🔥WIN BIG NOW!!,win free urgent offer limited limited urgent u...,1,🔥WIN BIG NOW!! win free urgent offer limited l...
3,🔥WIN BIG NOW!!,guarantee click now cash offer click now guara...,1,🔥WIN BIG NOW!! guarantee click now cash offer ...
4,Meeting Reminder,team sync - Significant property hotel not add...,0,Meeting Reminder team sync - Significant prope...
...,...,...,...,...
9995,🔥WIN BIG NOW!!,free win cash win guarantee urgent free win li...,1,🔥WIN BIG NOW!! free win cash win guarantee urg...
9996,You are selected!!!,click now free guarantee free win click now wi...,1,You are selected!!! click now free guarantee f...
9997,You are selected!!!,offer cash win limited click now cash limited ...,1,You are selected!!! offer cash win limited cli...
9998,Meeting Reminder,budget review - Many result affect idea.,0,Meeting Reminder budget review - Many result a...
9999,Schedule Confirmation,budget review - Day measure few alone decade a...,0,Schedule Confirmation budget review - Day meas...

In [9]:
clean_data=clean_data[["cleaned","label"]]

In [10]:
clean_data

                                                cleaned  label
0     Weekly Report budget review - Statement our I ...      0
1     Project Update team sync - President series to...      0
2     🔥WIN BIG NOW!! win free urgent offer limited l...      1
3     🔥WIN BIG NOW!! guarantee click now cash offer ...      1
4     Meeting Reminder team sync - Significant prope...      0
...                                                 ...    ...
9995  🔥WIN BIG NOW!! free win cash win guarantee urg...      1
9996  You are selected!!! click now free guarantee f...      1
9997  You are selected!!! offer cash win limited cli...      1
9998  Meeting Reminder budget review - Many result a...      0
9999  Schedule Confirmation budget review - Day meas...      0

[10000 rows x 2 columns]

In [12]:
clean_data.to_csv(r"D:\Machine_Learning_Projects\Spam_detection\data\data_clean.csv", index=False)