In [1]:
import os

In [2]:
%pwd

'd:\\Machine_Learning_Projects\\Spam_detection\\research'

In [3]:
os.chdir("../")

In [4]:
%pwd

'd:\\Machine_Learning_Projects\\Spam_detection'

In [5]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [7]:
data=pd.read_csv(r"D:\Machine_Learning_Projects\Spam_detection\data\spam_email_dataset.csv")

In [8]:
data.head()

,email_id,subject,email_text,num_words,num_characters,num_exclamation_marks,num_links,has_suspicious_link,num_attachments,has_attachment,sender_email,sender_domain,sender_reputation_score,email_hour,email_day_of_week,is_weekend,num_recipients,contains_money_terms,contains_urgency_terms,label
0,0,Weekly Report,budget review - Statement our I claim world st...,19,114,0,2,0,2,1,lctvdzm@outlook.com,outlook.com,0.66,19,3,0,23,0,0,0
1,1,Project Update,team sync - President series today already. In...,18,114,0,7,0,0,0,pxyldmi@company.com,company.com,0.95,4,4,0,16,1,0,0
2,2,🔥WIN BIG NOW!!,win free urgent offer limited limited urgent u...,19,126,0,4,1,1,1,atvanls@unknownmail.cc,unknownmail.cc,0.68,3,0,0,10,1,1,1
3,3,🔥WIN BIG NOW!!,guarantee click now cash offer click now guara...,16,101,0,7,1,1,1,qalxcnf@chealdealz.xyz,chealdealz.xyz,0.69,19,5,1,25,1,1,1
4,4,Meeting Reminder,team sync - Significant property hotel not add...,18,111,0,7,1,2,1,xoiccxl@yahoo.com,yahoo.com,0.67,4,5,1,8,0,0,0

In [9]:
numeric=data.select_dtypes(exclude="object")

In [10]:
numeric.head()

,email_id,num_words,num_characters,num_exclamation_marks,num_links,has_suspicious_link,num_attachments,has_attachment,sender_reputation_score,email_hour,email_day_of_week,is_weekend,num_recipients,contains_money_terms,contains_urgency_terms,label
0,0,19,114,0,2,0,2,1,0.66,19,3,0,23,0,0,0
1,1,18,114,0,7,0,0,0,0.95,4,4,0,16,1,0,0
2,2,19,126,0,4,1,1,1,0.68,3,0,0,10,1,1,1
3,3,16,101,0,7,1,1,1,0.69,19,5,1,25,1,1,1
4,4,18,111,0,7,1,2,1,0.67,4,5,1,8,0,0,0

In [11]:
category=data.select_dtypes(include="object")

In [12]:
category.head()

,subject,email_text,sender_email,sender_domain
0,Weekly Report,budget review - Statement our I claim world st...,lctvdzm@outlook.com,outlook.com
1,Project Update,team sync - President series today already. In...,pxyldmi@company.com,company.com
2,🔥WIN BIG NOW!!,win free urgent offer limited limited urgent u...,atvanls@unknownmail.cc,unknownmail.cc
3,🔥WIN BIG NOW!!,guarantee click now cash offer click now guara...,qalxcnf@chealdealz.xyz,chealdealz.xyz
4,Meeting Reminder,team sync - Significant property hotel not add...,xoiccxl@yahoo.com,yahoo.com

In [13]:
category.nunique()

subject              8
email_text       10000
sender_email     10000
sender_domain        8
dtype: int64

In [14]:
data1=data[["subject","email_text","label"]]

In [15]:
data1

,subject,email_text,label
0,Weekly Report,budget review - Statement our I claim world st...,0
1,Project Update,team sync - President series today already. In...,0
2,🔥WIN BIG NOW!!,win free urgent offer limited limited urgent u...,1
3,🔥WIN BIG NOW!!,guarantee click now cash offer click now guara...,1
4,Meeting Reminder,team sync - Significant property hotel not add...,0
...,...,...,...
9995,🔥WIN BIG NOW!!,free win cash win guarantee urgent free win li...,1
9996,You are selected!!!,click now free guarantee free win click now wi...,1
9997,You are selected!!!,offer cash win limited click now cash limited ...,1
9998,Meeting Reminder,budget review - Many result affect idea.,0
9999,Schedule Confirmation,budget review - Day measure few alone decade a...,0

In [16]:
data1["label"].value_counts()

label
0    6005
1    3995
Name: count, dtype: int64

In [17]:
data1

,subject,email_text,label
0,Weekly Report,budget review - Statement our I claim world st...,0
1,Project Update,team sync - President series today already. In...,0
2,🔥WIN BIG NOW!!,win free urgent offer limited limited urgent u...,1
3,🔥WIN BIG NOW!!,guarantee click now cash offer click now guara...,1
4,Meeting Reminder,team sync - Significant property hotel not add...,0
...,...,...,...
9995,🔥WIN BIG NOW!!,free win cash win guarantee urgent free win li...,1
9996,You are selected!!!,click now free guarantee free win click now wi...,1
9997,You are selected!!!,offer cash win limited click now cash limited ...,1
9998,Meeting Reminder,budget review - Many result affect idea.,0
9999,Schedule Confirmation,budget review - Day measure few alone decade a...,0

In [ ]:
import nltk
nltk.download("stopwords")
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
stopword=stopwords.words("english")

In [ ]:
import re
ps=PorterStemmer()

In [ ]:
def preprocess(data):
    text=re.sub("[^a-z,A-Z,0-9]"," ",data)
    text=text.lower().split()
    text=[ps.stem(i) for i in text if i not in stopword]
    return " ".join(text)

In [ ]:
data1["data_clean"]=(data1["subject"]+" "+data1["email_text"]).apply(preprocess)

In [ ]:
data1

In [ ]:

data2=data1[["data_clean","label"]]

In [ ]:
data2

In [ ]:
data2.isnull().sum()

In [ ]:
# pip install WordCloud

In [ ]:
spam=" ".join([word for word in data2[data2["label"]==1]["data_clean"]])
not_spam=" ".join([word for word in data2[data2["label"]==0]["data_clean"]])

In [ ]:
spam

In [ ]:
not_spam

In [ ]:
spam=[i for i in spam.split() if i not in not_spam]
not_spam=[i for i in not_spam.split() if i not in spam]

In [ ]:
words={}
for i in spam:
    if i in words:
        words[i]+=1
    else:
        words[i]=0
print(words)

In [ ]:
spam_df=pd.DataFrame({"spam_words":words.keys(),"num_characters":words.values()}).sort_values(by="num_characters",ascending=False).head(20)

In [ ]:
spam_df

In [ ]:
words={}
for i in not_spam:
    if i in words:
        words[i]+=1
    else:
        words[i]=0
print(words)

In [ ]:
not_spam_df=pd.DataFrame({"not_spam_words":words.keys(),"num_characters":words.values()})

In [ ]:
not_spam_df=not_spam_df.sort_values(by="num_characters",ascending=False).head(20)

In [ ]:
not_spam_df

In [ ]:
plt.figure(figsize=(16,6))
sns.barplot(data=not_spam_df,x="not_spam_words",y="num_characters")

In [ ]:
plt.figure(figsize=(14,6))
sns.barplot(data=spam_df,x="spam_words",y="num_characters")

In [ ]:
spam_review=" ".join(spam)
not_spam_review=" ".join(not_spam)

In [ ]:
spam_review

In [ ]:
from wordcloud import WordCloud
wc=WordCloud(background_color="white",max_words=40)
plt.imshow(wc.generate(spam_review))
plt.axis("off")
plt.show()

In [ ]:
wc=WordCloud(background_color="white",max_words=40)
plt.imshow(wc.generate(not_spam_review))
plt.axis("off")
plt.show()

In [ ]:
x=data2["data_clean"]
y=data2["label"]

In [ ]:
x

In [ ]:
y

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [ ]:
x_train

In [ ]:
cv=CountVectorizer()
x_train=cv.fit_transform(x_train)
x_test=cv.transform(x_test)

In [ ]:
x_train.toarray()

In [ ]:
x_test.toarray()

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier,AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
log=LogisticRegression()
log.fit(x_train,y_train)
y_pred=log.predict(x_test)
print(accuracy_score(y_test,y_pred)*100)

In [ ]:
user='''Subject: 🎉 Congratulations! You've Won ₹5,00,000!
Dear User,

We are pleased to inform you that you have been selected as the lucky winner of ₹5,00,000 in our international lottery program!

To claim your prize, please click the link below and provide your bank details for verification:
👉 http://claim-your-prize-now.com

Hurry! This offer is valid for a limited time only.

Congratulations once again!

Best Regards,
Lottery Promotion Team'''

In [ ]:
user=user.replace(","," ")

In [ ]:
user=preprocess(user)

In [ ]:
user=pd.Series([user])

In [ ]:
user

In [ ]:
user=cv.transform(user)

In [ ]:
user.toarray()

In [ ]:
log.predict(user)

In [ ]:
user1='''Subject: Project Meeting Update
Hi Team,

Just a quick update regarding our project meeting scheduled for tomorrow.

We will be discussing the current progress, pending tasks, and next steps. Please make sure to review your assigned work before the meeting and be prepared with any updates or questions.

Meeting Time: 10:00 AM
Location: Conference Room B / Zoom link will be shared shortly

Let me know if anyone has scheduling conflicts.

Best regards,
Rahul'''

In [ ]:
user1=user1.replace(","," ")
user1=preprocess(user1)
user1=pd.Series([user1])
user1=cv.transform(user1)
log.predict(user1)

In [ ]:
model={
    "Logistic Regression":LogisticRegression(),
    "KNeighbors Classifier":KNeighborsClassifier(),
    "Support Vector Machine":SVC(),
    "Decision Tree":DecisionTreeClassifier(),
    "Gaussian navie bayes":GaussianNB(),
    "Multinomial navie bayes":MultinomialNB(),
    "Bernoulli navie bayes":BernoulliNB(),
    "Random Forest Classifier":RandomForestClassifier(),
    ""
}